{{#if vpc}}
{{#if vpc.new}}
EndpointSQS:
  Type: "AWS::EC2::VPCEndpoint"
  Properties:
    VpcId:
      Ref: VPC
    ServiceName: com.amazonaws.{{region}}.sqs
    VpcEndpointType: Interface
    PrivateDnsEnabled: true
    SubnetIds:
      "Fn::Split" : [ ",", {"Ref": Subnets} ]
    SecurityGroupIds:
      "Fn::Split" : [ ",", {"Ref": SecurityGroups} ]
{{/if}}
{{/if}}
