AWSTemplateFormatVersion: "2010-09-09"
Description: Panda Sky Mixin - SQS
{{#if vpc}}
Parameters:
  VPC:
    Type: String
  Subnets:
    Type: String
  AvailabilityZones:
    Type: String
  SecurityGroups:
    Type: String
  RouteTables:
    Type: String
{{/if}}

Resources:

  {{#if vpc}}
  EndpointSQS:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      VpcId: !Ref VPC
      ServiceName: com.amazonaws.{{region}}.sqs
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      SubnetIds: !Split [ ",", !Ref Subnets ]
      SecurityGroupIds: !Split [ ",", !Ref SecurityGroups ]
  {{/if}}
